### ISSUE TITLE
Error processing ftw structure

### ISSUE THREAD

**Issue by leoadec** [odf/webGavrog#1]
I am finding webGavrog very useful for visualizing the tiling of 3D nets. However, when I try to open this very simple ftw tiling, I see an error message "ERROR processing structure 0!!!"

> TILING
> NAME "ftw/Cu3Au ; PPT 1; [2112]; 3[4^4]+[4^12] = 3[4b^4]+[4b^12]"
> GROUP Pm-3m
> FACES 4
> 0.50000 0.00000 0.50000 
> 1.00000 0.00000 0.00000 
> 1.00000 0.50000 0.50000 
> 1.00000 0.00000 1.00000 
> END

**Comment by odf** [comment]
That turns out to be a genuine bug somewhere deep in the maths code, so thanks for reporting this!

**Comment by odf** [comment]
This problem should be fixed now.

**Technical explanation for my own future reference:** the `minimal()` function for D-symbols did not follow the convention that a covering map must exist that maps element 1 of the original symbol to element 1 of its minimal image.
