### ISSUE TITLE
Cannot build because of fatal: ambiguous argument '${GIT_REV}'

### ISSUE THREAD

**Issue by Lolcroc** [odf/webGavrog#9]
**To reproduce**
`npm run build-dev`

**Issue**
> webGavrog@0.0.0 build-dev C:\\*redacted*\webGavrog
> webpack --mode development --debug --devtool cheap-module-source-map --output-pathinfo
> fatal: ambiguous argument '${GIT_REV}': unknown revision or path not in the working tree.

GIT_REV is not listed as an environment variable according to https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables. 

**Replacing ${GIT_REV} with HEAD gives me another error instead**

> webGavrog@0.0.0 build-dev C:\\*redacted*\webGavrog
> webpack --mode development --debug --devtool cheap-module-source-map --output-pathinfo

> C:\\*redacted*\webGavrog\node_modules\node-elm-compiler\dist\index.js:85
>            .on('error', function (err) { throw (err); });
>                                          ^

> Error: spawn elm ENOENT
>    at notFoundError (C:\\*redacted*\webGavrog\node_modules\cross-spawn\lib\enoent.js:6:26)
>    at verifyENOENT (C:\\*redacted*\webGavrog\node_modules\cross-spawn\lib\enoent.js:40:16)
>    at ChildProcess.cp.emit (C:\\*redacted*\webGavrog\node_modules\cross-spawn\lib\enoent.js:27:25)

Unfortunately I have little experience with Git and no experience with Node.js whatsoever. I don't know if this has an easy solution.

**Comment by odf** [comment]
Thanks! It should be fixed now.

It seems that particular line in `webpack.config.js` had been broken for some time, but my various Unix systems all silently treated `${GIT_REV}` as an empty string.
